version: '3.9'

services:
  proxy-dev:
    image: nginx:alpine
    container_name: proxy_dev
    profiles:
      - dev
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./client/dist:/static
    restart: 'unless-stopped'
    networks:
      - backend
  proxy:
    image: nginx:alpine
    container_name: proxy
    profiles:
      - prod
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/static
    restart: 'unless-stopped'
    networks:
      - backend
  server:
    profiles:
      - prod
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
