on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ./deploy.key
          sudo chmod 600 ./deploy.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}

      - name: Create env file
        run: |
          cat <<\EOT >target_file
          {
              "env": "production",
              "secretKey": "${{ secrets.SECRET }}",
              "uniUsername": "${{ secrets.UNI_USERNAME }}",
              "uniPassword": "${{ secrets.UNI_PASSWORD }}",
              "accUsername": "${{ secrets.ACC_USERNAME }}",
              "accPassword": "${{ secrets.ACC_PASSWORD }}", 
              "accHost": "https://sync.academiccloud.de/remote.php/nonshib-webdav",
              "domain": "${{ secrets.DOMAIN }}"
          }
          EOT
      - name: Install PM2
        run: npm install --global pm2

      - name: Deploy
        run: git stash && ls -la && pm2 deploy ./ecosystem.config.js production
        env:
          DEPLOY_PM2_HOST: ${{secrets.DEPLOY_PM2_HOST}}
          DEPLOY_PM2_USER: ${{secrets.DEPLOY_PM2_USER}}